### ISSUE TITLE
Send Message in group issue

### ISSUE THREAD

**Issue by gowthaman-murugan** [simple-xmpp/node-simple-xmpp#53]
hi
 One to one 
    xmpp.send("user@localhost", "test message", false);

 One to group 
    xmpp.send("myGroup@chat.localhost", "test message", true);

  While sending message between two users it's working fine but while user send message to group it's not work.

**Comment by honeyTops** [comment]
Hi,
I am facing the same issue. Can you please tell me the solution for this issue.
