### ISSUE TITLE
xmpp disconnect and dont reconnect even if the reconnect attribute is set to true

### ISSUE THREAD

**Issue by Mo33n** [simple-xmpp/node-simple-xmpp#54]
File name : 
.\node_modules\simple-xmpp\node_modules\node-xmpp\node_modules\node-xmpp-client\node_modules\node-xmpp-core\lib\connection.js

method "onClose()" : "self.reconnect" and  this.reconnect" are undefine.

dont know why. 
I have fixed this issue on my local setup. by passing the reconnect variable and the connect method as an argument from node_modules\simple-xmpp\node_modules\node-xmpp\node_modules\node-xmpp-client\lib\session.js file.

**Comment by rosslazer** [comment]
@Mo33n Would you mind sharing you fix in a gist? I'm having a similar issue. It usually reconnects, but after 24 hours or so it stops.

**Comment by Mo33n** [comment]
@rosslazer  that was very old patch , may be the library owner has fixed that issue, you goto check with him .

what i was doing is passing "reconnect = true" flag in the _socketConnectionToHost method  inside \simple-xmpp\node_modules\node-xmpp-client\lib\session.js

**Comment by rosslazer** [comment]
Where is the PR that fixes this?

**Comment by Mo33n** [comment]
dont know, but this case is not reproducing with the latest code.
