### ISSUE TITLE
Architecture for multi-client application

### ISSUE THREAD

**Issue by shubham1172** [simple-xmpp/node-simple-xmpp#84]
Hey, for an instant messaging application with multiple clients, should one create multiple instances of XMPP clients? What is the best way to deal with this use case?

**Comment by silverbucket** [comment]
Correct, you should create a new instance for each account.

**Comment by shubham1172** [comment]
What'll be the best way to store an instance of XMPP client per user in the memory? Express-session or redis cannot save objects like these, I suppose :/

**Comment by silverbucket** [comment]
Yeah, you will need to have some sort of daemon which maintains the connection as long as you need to keep it open. You cannot store network connections like you can with normal objects as they require system resources to stay active. This is something I've been working on with github.com/sockethub/sockethub which abstracts protocol specifics, as well as maintaining state, away from web applications. It may not suit your needs, but might provide some inspiration for your use case, but I can't really provide any more suggestions without knowing more.
