### ISSUE TITLE
Regarding Chat history

### ISSUE THREAD

**Issue by SethiShivam** [simple-xmpp/node-simple-xmpp#89]
Hi Team ,

I am new to xmpp development. and i am using simple-xmpp library to create nodejs client.
Could you please tell me if we have any functionality for chat history which shows previous chat during a conversation  ,if not than how to do that ?
Regards
Sethi Shivam

**Comment by silverbucket** [comment]
@SethiShivam hello, this library is based on an old version of `node-xmpp` which has now been entirely rewritten as [xmpp.js](https://github.com/xmppjs/xmpp.js/) ... so this library is no longer going to be maintained, and all of my applications which use it will slowly be migrated over to using `xmpp.js` directly. So I would recommend starting there for your development.
