### ISSUE TITLE
Deprecate node-simple-xmpp ?

### ISSUE THREAD

**Issue by silverbucket** [simple-xmpp/node-simple-xmpp#98]
Hi @arunoda - with the development of https://github.com/xmppjs/xmpp.js/ I've migrated all of my projects there as the API is quite complete and well thought out. I no longer have any time or interest in maintaining this repository, and I imagine the same goes for you.

I would propose that we put a deprecation notice at the top of the readme (pointing visitors to xmpp.js) and archive the repository so it's read-only. What do you think?

**Comment by silverbucket** [comment]
Ping @arunoda  any thoughts?

**Comment by arunoda** [comment]
Hey, sorry I didn't notice this.
Just do as you wish. I am not involved with JS-related work lately.
So, I think I don't qualify for deciding anything :D
